### ISSUE TITLE
push failed

### ISSUE THREAD

**Issue by aycignl** [aycignl/HipoInternshipProject#4]
Actually, the app deploys on Heroku but there is a problem about 'static files'. 
The domain works functionally but it looks a little bit different from original site.

**Comment by gokceuludogan** [comment]
I have found some information [here](https://devcenter.heroku.com/articles/django-assets) which can be useful for you to solve this problem. By the way, the project is cool :smile:

**Comment by aycignl** [comment]
I tried this but the result is the same😔 Maybe I missed the important point so, I think I can try this one more time. Many thnx for your suggestion and attention Gokce👍🏼 The final version of this project on heroku is coming very soon😊

**Comment by gokceuludogan** [comment]
How about the solution [here](https://matthewphiong.com/managing-django-static-files-on-heroku)? :smile: Maybe, you can create a branch for this problem and commit the changes there, and thus, we can see whether you miss something or not while you are trying the solution.

**Comment by aycignl** [comment]
I found the problem. I need to comment out this line: **STATICFILES_DIRS = ( os.path.join(PROJECT_ROOT, '../static'),)** in _settings.py_.
Thank you so much for your time and suggestions Gokce.

**Comment by gokceuludogan** [comment]
Good job 👍
